In [33]:
import math as m

def hitung_bus(peserta, pendamping) :
  total_orang = peserta+pendamping
  total_bus_besar = int(total_orang/46)
  sisa_orang = total_orang % 46
  total_bus_kecil = m.ceil(sisa_orang/16)
  harga_bus_besar = total_bus_besar*800000
  harga_bus_kecil = total_bus_kecil*400000
  total_harga = harga_bus_besar + harga_bus_kecil
  print("Bus Besar : %d"%total_bus_besar)
  print("Bus Kecil : %d"%total_bus_kecil)
  print("Total Biaya Sewa Bus : %d"%total_harga)

In [34]:
hitung_bus(250, 7)

Bus Besar : 5
Bus Kecil : 2
Total Biaya Sewa Bus : 4800000

In [35]:
hitung_bus(300, 10)

Bus Besar : 6
Bus Kecil : 3
Total Biaya Sewa Bus : 6000000

In [36]:
hitung_bus(350, 12)

Bus Besar : 7
Bus Kecil : 3
Total Biaya Sewa Bus : 6800000

In [37]:
hitung_bus(0, 0)

Bus Besar : 0
Bus Kecil : 0
Total Biaya Sewa Bus : 0