In [5]:
def bubblesort(data):
    n = len(data)
    while True:
        tukar = False
        for i in range(n-1):
            if data[i] < data[i+1]:
                data[i], data[i+1] = data[i+1], data[i]
                tukar = True
                print(f"Tukar {data[i]} dengan {data[i+1]}")
                print("urutan menjadi ", data)
        if not tukar:
            break

In [6]:
a = [6,1,7,4,2,5]
bubblesort(a)

Tukar 7 dengan 1
urutan menjadi  [6, 7, 1, 4, 2, 5]
Tukar 4 dengan 1
urutan menjadi  [6, 7, 4, 1, 2, 5]
Tukar 2 dengan 1
urutan menjadi  [6, 7, 4, 2, 1, 5]
Tukar 5 dengan 1
urutan menjadi  [6, 7, 4, 2, 5, 1]
Tukar 7 dengan 6
urutan menjadi  [7, 6, 4, 2, 5, 1]
Tukar 5 dengan 2
urutan menjadi  [7, 6, 4, 5, 2, 1]
Tukar 5 dengan 4
urutan menjadi  [7, 6, 5, 4, 2, 1]